### ISSUE TITLE
Software protection 

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#16]
I'm wondering if you have any suggestions.  I want to make sure the software is not copied when I install at clients. Also, I want to make kitchen screen an option that customers have to pay for... How can I turn that function on and off.

**Comment by dalifreire** [comment]
@Alon76, yes, I can think about this. Could you talk more about your clients environment (how do you do these software installation, if exists internet so we can develop a backend or no, etc) by email?

**Comment by dalifreire** [comment]
Hi @Alon76,
To do this properly we will need a LOT of time (Apple go to extraordinary lengths to protect the software on the Iphone/Ipad, and yet jailbreak apps unlock them). It is much cheaper just buying a product which is designed to protect java programs (something like https://www.license4j.com/).

**Comment by Alon76** [comment]
I was thinking the same thing. I will have to look into options. I saw that software, but I will look into others.

**Comment by Alon76** [comment]
What do you think of this? 
http://afewguyscoding.com/2012/02/licensing-module-java/

**Comment by dalifreire** [comment]
@Alon76 looks interesting... but I'll need some time to understand and adapt the source code to our system.

**Comment by dalifreire** [comment]
Hi @Alon76,

I implemented a license file mechanism.. you can generate one license file (license.dat) using this jar (5starPOS-LicenseManager.jar). The generated license file is based on "template.dat" file. To generete the license file (license.dat) you must run the following code on terminal/comand: java -jar 5starPOS-LicenseManager.jar -t=template.dat 

![image](https://cloud.githubusercontent.com/assets/10319140/23439138/1c8cc2c8-fdf4-11e6-8100-dc5cf1d85d1e.png)

[5starPOS-LicenseManager.zip](https://github.com/Alon76/5starPOS/files/809261/5starPOS-LicenseManager.zip)

From now, the system will need this license.dat file to open... that's the new version:

[#16_5starPOS.zip](https://github.com/Alon76/5starPOS/files/809262/16_5starPOS.zip)

Please, check if it works as desired and let me know.

**Comment by Alon76** [comment]
I am a little confused. If someone takes both the files to another computer, then the system will run? I don't want the clients to be able to buy another computer and be able to copy the software over.

**Comment by dalifreire** [comment]
@Alon76 Yes, if the license file was copied into another computer the system will run.

I don't know a safe way to uniquely identify a computer... if you assume that a computer is built with many parts that can be replaced eventually, customers may replace something in their machine and will need an updated license to run your software... so the only safe solution that I can think for now is create a License Manager Server Application.

That is, when the software starts up, it queries a server on the network (internet) that validates that the customer's usage of the software is legitimate. But, we will need implement and publish this web service using something like [Amazon Web Services](https://aws.amazon.com) or [Microsoft Azure](https://azure.microsoft.com). The bad news is that's will need to pay a server monthly and will cost more then $ 160 that we have accorded by upwork.

Or I can implement something that catchs a "unique identifier" for the computer and unlocks the system only if the computer that is running matches... but I need to warn that maybe you will get a lot of phone calls asking for a new license when something changes in the computer...

**Comment by Alon76** [comment]
Ok, it makes sense. I think if i attach it to the motherboard identifier, then I should be fine. Most people wont bother changing the motherboard...they will usually just buy another computer. Should we just go with that?

**Comment by dalifreire** [comment]
@Alon76 Done! Use this new version os 5starPOS-LicenseManager.jar and template.dat. If the property MachineKey is blank or does not exists, so the generated license will create a machine key and the application will runs only for the machine where the license was generated. If the value for property MachineKey is equals to ************, so the generated license file will ignore the machine and tha application will runs in any machine.

[5starPOS-LicenseManager(2).zip](https://github.com/Alon76/5starPOS/files/819846/5starPOS-LicenseManager.2.zip)

You must use this new version of the system... you need to add 2 new .jars (oshi-core-3.4.2.jar and slf4j-api-1.7.24.jar) into the lib folder and replace the threetenbp-0.8.1.jar by a new version (threetenbp-1.3.3.jar)

[#16_5starPOS(2).zip](https://github.com/Alon76/5starPOS/files/819865/16_5starPOS.2.zip)

**Comment by Alon76** [comment]
Trying to get it working. The 3 jar files need to go into the lib folder? And the rest of the files go in the main folder?

**Comment by dalifreire** [comment]
@Alon76 yes! and the 5starPOS-LicenseManager(2).zip works alone... that is another application.

If your doubt remains you can download all again from here: https://drive.google.com/open?id=0B3a_d6KzQ1faYm1NRWVjMlR0bWM

**Comment by Alon76** [comment]
Every time I run, I get this error.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.platform.win32.Guid$GUID.createFieldsOrder([Ljava/lang/String;)Ljava/util/List;
        at com.sun.jna.platform.win32.Guid$GUID.<clinit>(Guid.java:108)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.proxy.$Proxy0.<clinit>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.reflect.Proxy.newProxyInstance(Unknown Source)
        at com.sun.jna.Native.loadLibrary(Native.java:506)
        at oshi.jna.platform.windows.Ole32.<clinit>(Ole32.java:35)
        at oshi.util.platform.windows.WmiUtil.initCOM(WmiUtil.java:374)
        at oshi.util.platform.windows.WmiUtil.queryWMI(WmiUtil.java:331)
        at oshi.util.platform.windows.WmiUtil.selectStringsFrom(WmiUtil.java:257)
        at oshi.hardware.platform.windows.WindowsComputerSystem.init(WindowsComputerSystem.java:43)
        at oshi.hardware.platform.windows.WindowsComputerSystem.<init>(WindowsComputerSystem.java:38)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getComputerSystem(WindowsHardwareAbstractionLayer.java:42)
        at com.floreantpos.license.FiveStarPOSLicenseManager.getMachineKey(FiveStarPOSLicenseManager.java:129)
        at com.floreantpos.license.FiveStarPOSLicenseManager.generateNewLicense(FiveStarPOSLicenseManager.java:250)
        at com.floreantpos.license.FiveStarPOSLicenseManager.main(FiveStarPOSLicenseManager.java:76)

Any suggestions?

**Comment by dalifreire** [comment]
Hi @Alon76 ,
Looks like something related to windows machines... I'll do some tests and let you know.

**Comment by dalifreire** [comment]
@Alon76 

I found what was the problem and I fixed it. Please, use this new one:

- https://drive.google.com/open?id=0B3a_d6KzQ1faUGlUakY0cG5nM2c

Was needed replace one of the libs... the _**jna-4.2.2.jar**_ must be replaced by _**jna-4.3.0.jar**_ and we need to use the new version of the _**floreantpos.jar**_ too. Please, check if everything is working well now.

**Comment by Alon76** [comment]
I still get an error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Is it supposed to look like this?

I downloaded the floreant folder you sent. Then I downloaded the license manager. Then I downloaded the last folder and overwrote the jar and the lib files. Is that right?

![untitled](https://cloud.githubusercontent.com/assets/21187721/24277852/486d94c4-1016-11e7-8964-ee60202ce409.png)

**Comment by Alon76** [comment]
Do I need Java development environment installed?

**Comment by dalifreire** [comment]
@Alon76, yes it's right and don't worry about this warning... it's related to logs that we don't include some dependencies (slf4j). This don't have impact in the application.

About your second question... absolutely no, the 5starPOS-LicenseManager will not to be included together with the application! Anyone with this application can generate a valid license.. so only you must use this. 

![image](https://cloud.githubusercontent.com/assets/10319140/24332609/13f17574-1220-11e7-9dc0-4baa89c1278a.png)

Don't forget that 5starPOS-LicenseManager.jar and floreantpos.jar are 2 different applications. You must use the 5starPOS-LicenseManager.jar only to generate your license files, ok? After that put the generated license.dat into the floreantpos main folder. You should never deliver the 5starPOS-LicenseManager to your clients.

**Comment by Alon76** [comment]
Works well. Thanks

**Comment by Alon76** [comment]
Question. I applied a license on my computer and then I changed my hard drive and now it is saying the license key is invalid, but if it connected to the motherboard, then it should still work.
I even deleted that license key and created a new one and it is still telling me the key is invalid?

**Comment by dalifreire** [comment]
@Alon76 If you create a new license, that new license must works as a valid license... and I'm using some infos from SO to generate the MachineKey... so I'll try to change this and let you know.

**Comment by dalifreire** [comment]
@Alon76 Please, send the generated license files (before and after change the HD)... I need to check it (I'm unable to do this kind of test from here).

**Comment by Alon76** [comment]
I created so many licenses trying to get it work, that I am not 100% these are the old and new ones. I am basing it on the date of last modified.


![licensenew](https://cloud.githubusercontent.com/assets/21187721/24588174/2b56428c-1791-11e7-9432-e76baec44632.jpg)
![licenseold](https://cloud.githubusercontent.com/assets/21187721/24588175/2b5881a0-1791-11e7-8301-499086338930.jpg)


Change them back to .dat files...it would let me send them as dat files.

Thanks!!

**Comment by dalifreire** [comment]
@Alon76, I was unable to found any problem in the samples that you send me... could you try to reproduce the problem and send me the license files and image prints for error messages?

I notice that looks like you are not customizing the template.dat file... note that you can customize the propresties like ExpirationDate (if you try to open the system after this date a error message will be displayed ), if the BackOffice function must be visible, if the KitchenDisplay function must be visible, etc.

**Comment by Alon76** [comment]
I will try to replicate the issue and I didn't realize you can edit the dat file.

**Comment by Alon76** [comment]
I must be doing something wrong because it's not working at all now. Even when I download the software from the google drive you sent, it is giving me the same error?

**Comment by Alon76** [comment]
Perhaps I can give you remote access to my computer and you can try. I went to another laptop and it is not working on that laptop as well.
Do I need to edit the template before I create the license? I have no idea why it is not working now...very strange.

**Comment by dalifreire** [comment]
Hi @Alon76, 

Yes, you must edit the template file before create the license file. The license file is generated based on template file. If you can send me print screens and log files, that's will help me to analyse what is going on.

I can take a look by remote access... please let me know what is the best hour for you in this saturday. Remind that I'm at [UTC-3](https://www.timeanddate.com/time/zones/brt).

**Comment by Alon76** [comment]
This is the error I get:

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Platform
        at oshi.SystemInfo.<clinit>(SystemInfo.java:59)
        at com.floreantpos.license.FiveStarPOSLicenseManager.getMachineKey(FiveStarPOSLicenseManager.java:126)
        at com.floreantpos.main.Application.checkLicense(Application.java:151)
        at com.floreantpos.main.Application.getLicense(Application.java:170)
        at com.floreantpos.ui.views.LoginView.createCenterPanel(LoginView.java:140)
        at com.floreantpos.ui.views.LoginView.<init>(LoginView.java:107)
        at com.floreantpos.ui.views.LoginView.getInstance(LoginView.java:314)
        at com.floreantpos.ui.views.order.RootView.initView(RootView.java:73)
        at com.floreantpos.ui.views.order.RootView.<init>(RootView.java:64)
        at com.floreantpos.ui.views.order.RootView.getInstance(RootView.java:144)
        at com.floreantpos.main.Application.start(Application.java:126)
        at com.floreantpos.main.Main.main(Main.java:51)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more

**Comment by dalifreire** [comment]
Hi @Alon76,

I downloaded the floreantpos.zip and 5starPOS-LicenseManager(3).zip files from https://drive.google.com/open?id=0B3a_d6KzQ1faUGlUakY0cG5nM2c. I run on linux and windows machines and everything works well here... so, I need you describe for me what are you doing to create the license and run the application. 

I just open the template license and changed the expiration date property: 
![image](https://cloud.githubusercontent.com/assets/10319140/25063898/9a4c18fe-21c5-11e7-908e-6e38706cee12.png)

I did run the licence manager application informing the template file and a new license file was created:
`java -jar 5starPOS-LicenseManager.jar -t=template.dat`

![image](https://cloud.githubusercontent.com/assets/10319140/25063920/f87fdd34-21c5-11e7-97e9-426e5878f8a8.png)

![image](https://cloud.githubusercontent.com/assets/10319140/25063915/dac2c004-21c5-11e7-9fc6-e6e19beba768.png)

Put the new license file into the root folder and run the application:
![image](https://cloud.githubusercontent.com/assets/10319140/25063925/16f22b14-21c6-11e7-8bab-1a2aa3cb79a4.png)

![image](https://cloud.githubusercontent.com/assets/10319140/25063937/400ab8a4-21c6-11e7-9583-d137a86e0477.png)
